"""Stems that identify a symptom in English, Tamil and Tanglish, used to tell when a patient DENIES it.

The ML model must never act on a symptom the text says the patient does not have ("no bleeding",
"நெஞ்சு வலி இல்லை"). triage.condition_denied() looks for the condition's protocol keywords and also for these
simple stems — the protocol keywords are phrases like "heavy bleeding", so a plain "no bleeding" would otherwise
go unnoticed. A trailing '*' makes a stem a prefix, as in the protocol keywords.

The website reads website/js/denial.js, generated from this file:  python -m medos.denial
"""
from __future__ import annotations

from pathlib import Path

# Deliberately NOT here: Breathing difficulty and Stroke signs. For those, a negated phrase IS the emergency
# ("he is not breathing", "மூச்சு இல்லை", "can't speak"), so a bare stem plus a negation must never count as a denial.
# They are denied only through explicit protocol phrases ("no breathing difficulty", "மூச்சு திணறல் இல்லை").
# Unconscious / collapsed has only the dizzy / faint words: "மயக்கம் இல்லை" ("no dizziness") is a denial, while
# "not waking up" or "சுயநினைவு இல்லை" (no consciousness) is the emergency and is not listed.
DENIAL_STEMS = {
    "Chest pain / suspected heart attack": ["chest pain*", "chest tight*", "chest pressure", "heart attack", "நெஞ்சு*", "மார்பு*", "nenju*", "maarbu*"],
    "Severe bleeding": ["bleed*", "blood*", "ரத்த*", "இரத்த*", "ratham*", "ratha*"],
    "Seizure": ["seizure*", "fits", "convuls*", "வலிப்பு*", "ஜன்னி*", "valippu*"],
    "Severe allergic reaction": ["allerg*", "anaphyla*", "swell*", "swollen*", "அலர்ஜி*", "வீங்*", "veeng*"],
    "Major trauma": ["accident*", "head injury", "fall from*", "fell from*", "விபத்து*", "accident*"],
    "Poisoning / bite / overdose": ["poison*", "overdose*", "snake*", "bite*", "bitten", "விஷ*", "பாம்பு*", "paambu*", "visham*"],
    "Severe burns / electric shock": ["burn*", "electric*", "scald*", "தீக்காய*", "கரண்ட்*", "current adi*"],
    "Severe abdominal pain": ["abdominal*", "stomach*", "belly*", "tummy*", "வயிறு*", "வயித்து*", "vayiru*"],
    "Fracture": ["fractur*", "broken*", "broke*", "எலும்பு*", "elumbu*"],
    "High fever (>102°F)": ["fever*", "temperature*", "காய்ச்சல்*", "ஜுரம்*", "kaichal*", "juram*"],
    "Severe migraine/headache": ["headache*", "migraine*", "தலைவலி*", "தலை வலி*", "thalaivali*"],
    "Persistent vomiting": ["vomit*", "வாந்தி*", "vaanthi*"],
    "Asthma attack (mild)": ["asthma*", "wheez*", "ஆஸ்துமா*", "வீசிங்*"],
    "Unconscious / collapsed": ["dizz*", "மயக்கம்*", "மயக்கமா*", "mayakkam*", "mayakama*"],
}


def write_js(path: Path) -> None:
    import json
    path.write_text(
        "// Generated by `python -m medos.denial` from medos/denial.py — edit that file, not this one.\n"
        "\"use strict\";\n"
        "const DENIAL_STEMS = " + json.dumps(DENIAL_STEMS, ensure_ascii=False, indent=1) + ";\n",
        encoding="utf-8")


if __name__ == "__main__":
    out = Path(__file__).resolve().parent.parent / "website" / "js" / "denial.js"
    write_js(out)
    print("Wrote", out)
