"""Tamil (and Tanglish) words for the triage protocol.

Patients speak Tamil, English or a mix. The speech recogniser writes Tamil in Tamil script, and often
writes English medical words in Tamil script too (ஃபீவர், சுகர்). These keywords are added to the
protocol conditions in medos/triage.py, using the same matching rules:

    word*      prefix — Tamil adds endings (வலி, வலிக்குது, வலியா), so most entries are prefixes
    a+b        both parts in the same sentence, in any order ("நெஞ்சு ... வலி")

Tamil puts negation AFTER the word ("நெஞ்சு வலி இல்லை" = no chest pain); TAMIL_NEGATION is checked
just after a match. The website uses the same lists (website/js/triage_tamil.js, generated by
`python -m medos.triage_tamil`).
"""
from __future__ import annotations

TAMIL_KEYWORDS = {
    # ---- red flags (always Critical)
    "Chest pain / suspected heart attack": [
        "நெஞ்சு வலி*", "நெஞ்சுவலி*", "நெஞ்சு*+வலி*", "நெஞ்சில்+வலி*", "நெஞ்சு*+அடைப்ப*", "நெஞ்சு*+பாரம*",
        "மார்பு வலி*", "மார்பு*+வலி*", "மாரடைப்*", "ஹார்ட் அட்டாக்*", "இதய வலி*",
        "nenju vali", "nenjuvali", "nenju+vali*", "nenju+adaippu"],
    "Breathing difficulty": [
        "மூச்சு திணற*", "மூச்சுத்திணற*", "மூச்சு*+திணற*", "மூச்சு விட முடிய*", "மூச்சு*+முடியல*",
        "மூச்சு*+கஷ்ட*", "மூச்சு*+சிரம*", "மூச்சு வாங்க*", "மூச்சு இரைப்*",
        # "மூச்சே வரல" / "மூச்சு வரவே இல்ல" = no breath is coming (the negation belongs to the verb)
        "மூச்சே வர*", "மூச்சு*+வரவே இல்*", "மூச்சு*+வரல*",
        "moochu thinaral*", "moochu+mudiyala", "moochu+kashtam", "moochu*+varave ill*", "moochu*+varala*"],
    "Stroke signs": [
        "பக்கவாத*", "ஸ்ட்ரோக்*", "வாய்+கோணி*", "வாய் கோண*", "பேச்சு+குழற*", "ஒரு பக்கம்+செயலிழ*",
        "ஒரு பக்கம்+வராம*", "கை கால்+விழுந்துடுச்*", "pakkavatham*"],
    "Unconscious / collapsed": [
        # "மயக்கமா இருக்கு" / "mayakkam" usually means "I feel dizzy", so only clear collapse phrases are here.
        "மயங்கி விழு*", "மயங்கி விழுந்த*", "மயக்கம் அடை*", "மயக்கமாகி விழு*", "நினைவு இழ*",
        # Tamil negates after the word, so "இல்லை" belongs inside these phrases ("சுயநினைவு இல்லை" = unconscious)
        "சுயநினைவு இல்*", "நினைவு இல்லாம*", "எழுந்திருக்கல*", "எழுந்திருக்கவே இல்*", "கண்ணே திறக்க*", "பேச்சு மூச்சு இல்*",
        "mayangi vizhunthu*", "ezhunthirikkave ill*", "ezhunthirikkala*"],
    "Severe bleeding": [
        # "நிற்கவே இல்லை" = won't stop: the negation is part of the phrase, not a "no bleeding"
        "ரத்தம்*+நிற்கவே இல்*", "ரத்தம்*+நிக்கவே இல்*", "ரத்தம்*+நிக்கல*", "ரத்தம்*+நிற்கல*",
        "இரத்தம்*+நிற்கவே இல்*", "இரத்தம்*+நிற்கல*", "ரத்தப்போக்கு*", "இரத்தப்போக்கு*", "ரத்த வாந்தி*", "இரத்த வாந்தி*",
        "நிறைய ரத்தம்*", "நிறைய இரத்தம்*", "அதிக ரத்த*", "அதிக இரத்த*", "ரத்தம் கொட்டு*", "ரத்தம் வழி*",
        "ratham+nikkala", "ratha vaanthi",
        # "won't stop" idioms: the negation belongs to the verb, not to the blood
        "ratham*+nikkave ill*", "ratham*+nikkala*", "ratham*+nikka*", "ரத்தம்*+நிக்காம*", "ரத்தம்*+நிற்காம*"],
    "Seizure": ["வலிப்பு*", "ஜன்னி*", "பிட்ஸ்*", "காக்காய் வலிப்பு*", "valippu", "fits vandhu*", "valippu*+theliyave ill*"],
    "Severe allergic reaction": [
        "தொண்டை வீங்*", "நாக்கு வீங்*", "முகம் வீங்*+மூச்சு*", "உதடு வீங்*+மூச்சு*", "அலர்ஜி*+மூச்சு*"],
    "Major trauma": [
        "விபத்து*", "ஆக்சிடென்ட்*", "ஆக்ஸிடென்ட்*", "தலையில் அடி*", "தலையில அடி*", "தலை*+அடிபட்*",
        "உயரத்தில் இருந்து விழு*", "உயரத்தில இருந்து விழு*", "மாடியில் இருந்து விழு*", "மாடியில இருந்து விழு*",
        "மரத்தில் இருந்து விழு*", "மரத்தில இருந்து விழு*", "கத்தி குத்*", "கத்தியால் குத்*", "கத்தியால குத்*",
        "வண்டி மோதி*", "லாரி மோதி*", "பஸ் மோதி*",
        "vibathu", "accident aagi*"],
    "Poisoning / bite / overdose": [
        "விஷம்*", "விஷத்த*", "பூச்சி மருந்து*", "பூச்சிக்கொல்லி*", "பாம்பு கடி*", "பாம்பு*+கடி*", "தேள் கடி*",
        "தேள்*+கொட்டு*", "மாத்திரை*+நிறைய*", "எலி மருந்து*", "மண்ணெண்ணெய்*", "தற்கொலை*",
        "paambu kadi*", "paambu+kadi*", "visham"],
    "Severe burns / electric shock": [
        "தீக்காய*", "தீ காய*", "தீ பிடி*", "தீப்பிடி*", "கரண்ட் அடி*", "கரண்ட் ஷாக்*", "மின்சாரம் தாக்*",
        "ஷாக் அடி*", "ஆசிட்*", "சுடு தண்ணீர்*+கொட்*", "current adichi*", "theekkaayam*"],
    # ---- the priority table
    "Severe abdominal pain": [
        "வயிறு*+பயங்கர*", "வயிறு*+தாங்க முடிய*", "வயிற்று*+கடுமைய*", "வயிற்று*+தாங்க முடிய*", "வயித்து*+பயங்கர*",
        # "ரொம்ப" = very / a lot: like the English "very bad stomach pain", this is the severe row
        "ரொம்ப வயிறு வலி*", "வயிறு ரொம்ப வலி*", "ரொம்ப வயித்து வலி*", "வயித்து வலி ரொம்ப*",
        "அப்பெண்டிக்ஸ்*", "குடல்வால்*", "vayiru+thanga mudiyala", "romba vayiru vali*", "vayiru romba vali*"],
    "Fracture": [
        "எலும்பு முறி*", "எலும்பு*+உடை*", "எலும்பு*+முறி*", "ஃப்ராக்சர்*", "பிராக்சர்*", "மூட்டு விலக*",
        "elumbu+odainju*", "fracture aagi*"],
    "High fever (>102°F)": [
        "அதிக காய்ச்சல்*", "கடும் காய்ச்சல்*", "கடுமையான காய்ச்சல்*", "காய்ச்சல்*+நடுக்க*", "குளிர் காய்ச்சல்*",
        "காய்ச்சல்*+உதற*", "ரொம்ப காய்ச்சல்*", "high fever", "romba kaichal*",
        "காய்ச்சல்*+குறையவே இல்*", "காய்ச்சல்*+குறையல*", "kaichal*+kuraiyave ill*", "kaichal*+kuraiyala*"],
    "Severe migraine/headache": [
        "ஒற்றைத் தலைவலி*", "ஒற்றை தலைவலி*", "ஒத்த தலைவலி*", "மைக்ரேன்*", "கடுமையான தலைவலி*",
        "தலைவலி*+தாங்க முடிய*", "தலை வலி*+தாங்க முடிய*", "romba thalai vali*"],
    "Persistent vomiting": [
        "வாந்தி*+நிற்கவே இல்*", "வாந்தி*+நிக்கவே இல்*", "வாந்தி*+நிக்கல*", "வாந்தி*+நிற்கல*", "நிக்காம வாந்தி*",
        "நிற்காமல் வாந்தி*", "திரும்பத் திரும்ப வாந்தி*", "தொடர்ந்து வாந்தி*", "நிறைய தடவை வாந்தி*", "வாந்தி*+பேதி*",
        "vaanthi+nikkala", "nikkama vaanthi*", "vaanthi+bedhi", "vaanthi*+nikkave ill*", "vaanthi*+nikkala*"],
    "Asthma attack (mild)": ["ஆஸ்துமா*", "இழுப்பு*", "வீசிங்*", "இன்ஹேலர்*", "izhuppu"],
    "Chest infection": ["நெஞ்சு சளி*", "நெஞ்சுச்சளி*", "நிமோனியா*", "சளியுடன் இருமல்*", "கபம்*", "nenju sali"],
    "Back pain": ["முதுகு வலி*", "முதுகுவலி*", "இடுப்பு வலி*", "கழுத்து வலி*", "mudhugu vali*", "idupu vali*"],
    "Stomach pain (mild)": [
        "வயிறு வலி*", "வயிற்று வலி*", "வயித்து வலி*", "வயிறு*+வலி*", "வயித்து*+வலி*", "வாந்தி*", "பேதி*",
        "வயிற்றுப்போக்கு*", "அஜீரண*", "கேஸ் ட்ரபுள்*", "அசிடிட்டி*", "vayiru vali*", "vayithu vali*", "vaanthi", "bedhi"],
    "Ear pain": ["காது வலி*", "காதுவலி*", "காது*+வலி*", "kaadhu vali*"],
    "Sore throat": ["தொண்டை வலி*", "தொண்டைவலி*", "தொண்டை*+கரகர*", "டான்சில்*", "thondai vali*"],
    "Skin allergy/rash": ["அரிப்பு*", "தடிப்பு*", "சொறி*", "தோல்*+அலர்ஜி*", "அலர்ஜி*", "arippu"],
    "Cold & cough": ["சளி*", "இருமல்*", "தும்மல்*", "மூக்கு ஒழுக*", "ஜலதோஷ*", "irumal", "sali"],
    "Mild fever": ["காய்ச்சல்*", "ஜுரம்*", "ஜூரம்*", "சுரம்*", "உடம்பு வலி*", "ஃபீவர்*", "kaichal", "juram"],
    "Routine check-up": ["செக்கப்*", "செக் அப்*", "சுகர் செக்*", "பிபி செக்*", "மருந்து வாங்க*", "தடுப்பூசி*", "check up ku"],
}

# Tamil negation follows the word: "நெஞ்சு வலி இல்லை", "காய்ச்சல் கிடையாது", "vali illa".
TAMIL_NEGATION = r"^[^,.;!?\n]{0,12}?(இல்லை|இல்ல|கிடையாது|இல்லாம|illa|illai|kidaiyathu)"


def merged(conditions):
    """The protocol conditions with the Tamil keywords added (no duplicates)."""
    out = []
    for c in conditions:
        extra = [k for k in TAMIL_KEYWORDS.get(c["name"], []) if k not in c["keywords"]]
        out.append({**c, "keywords": list(c["keywords"]) + extra})
    return out


def write_js(path) -> None:
    """Generate website/js/triage_tamil.js from the lists above."""
    import json
    path.write_text(
        "// Generated by `python -m medos.triage_tamil` from medos/triage_tamil.py — edit that file, not this one.\n"
        "\"use strict\";\n"
        "const TAMIL_KEYWORDS = " + json.dumps(TAMIL_KEYWORDS, ensure_ascii=False, indent=1) + ";\n"
        "const TAMIL_NEGATION = new RegExp(" + json.dumps(TAMIL_NEGATION, ensure_ascii=False) + ");\n",
        encoding="utf-8")


if __name__ == "__main__":
    from pathlib import Path
    out = Path(__file__).resolve().parent.parent / "website" / "js" / "triage_tamil.js"
    write_js(out)
    print("Wrote", out)
