// Generated by `python -m medos.denial` from medos/denial.py — edit that file, not this one.
"use strict";
const DENIAL_STEMS = {
 "Chest pain / suspected heart attack": [
  "chest pain*",
  "chest tight*",
  "chest pressure",
  "heart attack",
  "நெஞ்சு*",
  "மார்பு*",
  "nenju*",
  "maarbu*"
 ],
 "Severe bleeding": [
  "bleed*",
  "blood*",
  "ரத்த*",
  "இரத்த*",
  "ratham*",
  "ratha*"
 ],
 "Seizure": [
  "seizure*",
  "fits",
  "convuls*",
  "வலிப்பு*",
  "ஜன்னி*",
  "valippu*"
 ],
 "Severe allergic reaction": [
  "allerg*",
  "anaphyla*",
  "swell*",
  "swollen*",
  "அலர்ஜி*",
  "வீங்*",
  "veeng*"
 ],
 "Major trauma": [
  "accident*",
  "head injury",
  "fall from*",
  "fell from*",
  "விபத்து*",
  "accident*"
 ],
 "Poisoning / bite / overdose": [
  "poison*",
  "overdose*",
  "snake*",
  "bite*",
  "bitten",
  "விஷ*",
  "பாம்பு*",
  "paambu*",
  "visham*"
 ],
 "Severe burns / electric shock": [
  "burn*",
  "electric*",
  "scald*",
  "தீக்காய*",
  "கரண்ட்*",
  "current adi*"
 ],
 "Severe abdominal pain": [
  "abdominal*",
  "stomach*",
  "belly*",
  "tummy*",
  "வயிறு*",
  "வயித்து*",
  "vayiru*"
 ],
 "Fracture": [
  "fractur*",
  "broken*",
  "broke*",
  "எலும்பு*",
  "elumbu*"
 ],
 "High fever (>102°F)": [
  "fever*",
  "temperature*",
  "காய்ச்சல்*",
  "ஜுரம்*",
  "kaichal*",
  "juram*"
 ],
 "Severe migraine/headache": [
  "headache*",
  "migraine*",
  "தலைவலி*",
  "தலை வலி*",
  "thalaivali*"
 ],
 "Persistent vomiting": [
  "vomit*",
  "வாந்தி*",
  "vaanthi*"
 ],
 "Asthma attack (mild)": [
  "asthma*",
  "wheez*",
  "ஆஸ்துமா*",
  "வீசிங்*"
 ],
 "Unconscious / collapsed": [
  "dizz*",
  "மயக்கம்*",
  "மயக்கமா*",
  "mayakkam*",
  "mayakama*"
 ]
};
